server:
<<<<<<< HEAD
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/permissiondb?serverTimezone=UTC&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver


    thymeleaf:
      prefix: classpath:/templates/
      mode: LEGACYHTML5
      cache: false
#
#
mybatis:
    config-location: classpath:config/mybatis-config.xml
=======
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro
logging:
  config: classpth:config/logback.xml
mybatis:
  mapper-locations: classpath*:com/ccm/**/dao/*.xml
  configuration: classpath:config/mybatis-config.xml
>>>>>>> master
