server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy:

  thymeleaf:
#    prefix: classpath:resource/templates/
    mode: LEGACYHTML5
    cache: false


mybatis:
  mapper-locations: classpath*:com.ccm.permission/**/dao/*.xml
  configuration: classpath:config/mybatis-config.xml


#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

#Swagger lock
#swagger:
#  enabled: true

